#! /bin/bash

PROFILES=$(aws configure list-profiles)
CHOICE=$1
if [ -z "$1" ];  then
    CHOICE=$(echo "$PROFILES" | fzf )
fi

if ! echo "${PROFILES}" | grep -Eq "^${CHOICE}$" ; then
    echo "Cowardly refusing to open AWS SHELL for profile $1"
    echo "No such profile in ~/.aws/profile"
    exit 1
fi

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

AWS_PROFILE=$CHOICE PS1="\[${green}\]AWS [\[${red}\]$AWS_PROFILE\[${green}\]]:\[${reset}\] \w $ " bash
